services:
  slurmjupyter:
        image: slurm-reframe
        build: ./reframe
        container_name: rfmfrontend
        command: bash
        user: admin
        volumes:
                - shared-vol:/home/admin
  slurmmaster:
        image: slurm-master
        build: ./master
        hostname: slurmmaster
        container_name: slurmmaster
        user: admin
        volumes:
                - shared-vol:/home/admin
        environment:
                - SLURM_CPUS_ON_NODE=1

  slurmnode1:
        image: slurm-node
        build: ./node
        hostname: slurmnode1
        container_name: slurmnode1
        user: admin
        volumes:
                - shared-vol:/home/admin
        environment:
                - SLURM_NODENAME=slurmnode1
                - SLURM_CPUS_ON_NODE=2
        links:
                - slurmmaster
  slurmnode2:
        image: slurm-node
        build: ./node
        hostname: slurmnode2
        container_name: slurmnode2
        user: admin
        volumes:
                - shared-vol:/home/admin
        environment:
                - SLURM_NODENAME=slurmnode2
                - SLURM_CPUS_ON_NODE=1
        links:
                - slurmmaster
  slurmnode3:
        image: slurm-node
        build: ./node
        hostname: slurmnode3
        container_name: slurmnode3
        user: admin
        volumes:
                - shared-vol:/home/admin
        environment:
                - SLURM_NODENAME=slurmnode3
                - SLURM_CPUS_ON_NODE=1
        links:
                - slurmmaster
volumes:
        shared-vol:
